/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#be0038",
        "on-error": "#ffffff",
        "outline": "#906f70",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "tertiary": "#5c5c5c",
        "outline-variant": "#e5bdbe",
        "surface-container-high": "#e8e8e8",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#1b1c1c",
        "tertiary-fixed": "#e3e2e2",
        "on-tertiary-fixed-variant": "#464747",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        "surface-container": "#eeeeee",
        "on-background": "#1a1c1c",
        "on-primary-fixed": "#40000d",
        "on-error-container": "#93000a",
        "primary-container": "#e21e4a",
        "on-secondary-container": "#636262",
        "on-surface": "#1a1c1c",
        "on-tertiary-fixed": "#1b1c1c",
        "error": "#ba1a1a",
        "on-surface-variant": "#5c3f41",
        "on-primary-container": "#fffbff",
        "surface-dim": "#dadada",
        "on-tertiary-container": "#fefcfc",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#474746",
        "surface-variant": "#e2e2e2",
        "on-primary-fixed-variant": "#920029",
        "primary-fixed": "#ffdada",
        "primary-fixed-dim": "#ffb2b6",
        "surface-container-highest": "#e2e2e2",
        "surface-container-low": "#f3f3f4",
        "secondary-fixed": "#e5e2e1",
        "secondary-container": "#e2dfde",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb2b6",
        "tertiary-container": "#747474",
        "surface-container-lowest": "#ffffff",
        "primary": "#ba0036",
        "surface": "#f9f9f9",
        "tertiary-fixed-dim": "#c7c6c6",
        "secondary": "#5f5e5e",
        "background": "#f9f9f9",
        "inverse-surface": "#2f3131",
        rausch: '#ff385c',
        dark: '#222222',
        subtle: '#6a6a6a',
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      boxShadow: {
        'ambient': 'rgba(0,0,0,0.02) 0px 0px 0px 1px, rgba(0,0,0,0.04) 0px 2px 6px, rgba(0,0,0,0.1) 0px 4px 8px',
        'ambient-hover': 'rgba(0,0,0,0.02) 0px 0px 0px 1px, rgba(0,0,0,0.06) 0px 4px 12px, rgba(0,0,0,0.12) 0px 8px 16px',
      }
    },
  },
  plugins: [],
}
